### ISSUE TITLE
Error and warning when compiling on OSX 10.10

### ISSUE THREAD

**Issue by boterpoes** [deadpixi/mtm#14]
I just tried to compile mtm on OSX, and I received the following error:

    mtm.c:339:32: error: use of undeclared identifier 'A_ITALIC'

and the following warning:

    mtm.c:676:5: warning: implicit declaration of function 'ioctl' is invalid in C99 [-Wimplicit-function-declaration]

How would I go about solving this? :)

**Comment by deadpixi** [comment]
Hi @boterpoes 

Sorry for the delay in responding. We're busy moving to a new city. :)

Please check the latest code in master and let me know if that works for you. If so, please close this ticket. Thanks.

**Comment by deadpixi** [comment]
Hi @boterpoes 

I think this issue is fixed, so I"m going to go ahead and close it. Please reopen it if that's not the case. Thanks.

**Comment by boterpoes** [comment]
Hi @deadpixi 

Sorry for the delay, I only got an e-mail of your last reply so I never saw the first.

Anyway, thanks a lot for responding! The newest master lets me build `mtm` indeed (with `CURSESLIB=curses`). However, it immeditately segfaults on me when running it. As that probably is out of scope for this issue, I'll open a new one :)

Good luck moving! Hope you'll enjoy your new home :)
