### ISSUE TITLE
h and v options are inverted

### ISSUE THREAD

**Issue by deathtrip** [deadpixi/mtm#15]
I'm using the Arch Linux AUR package, and as the title says the options are inverted.
h splits vertically, and v horizontally. I checked the PKGBUILD and didn't find any compile time changes that could cause this. So, is it a problem with mtm or asome weird package issue?

**Comment by deadpixi** [comment]
It's entirely possible that I didn't describe the operation correctly in the documentation. The "horizontal" and "vertical" notations really refer to how things are stacked, not how they are split.

**Comment by deathtrip** [comment]
I think you should consider switching these options, to how things are split, as right now they are very counterintuitive, and make switching from tmux pretty difficult. And only few people compile directly from git to change them at compilation time.

**Comment by deadpixi** [comment]
I went ahead and flipped the meaning; please see the latest code in master. I'm going to go ahead and close this issue but please reopen it if you have any questions.

**Comment by deathtrip** [comment]
It looks like you changed the internal names, instead of the shortcuts, as the program still works the same.
