### ISSUE TITLE
mtm is not showing 256 colors and not even 16 color

### ISSUE THREAD

**Issue by fedemp** [deadpixi/mtm#18]
From the screenshots in the Readme, I understand there should be some color support.

Currently using xfce4-terminal, I ran this script.

```
for i in {0..15} ; do                                                                  ~
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done
```

Left is output outside mtm, and right is inside mtm. `$TERM` inside mtm is `eterm-color`. After installing mtm terminfo, wwitching to `mtm -t mtm` doesn't make any difference.

![mtm](https://user-images.githubusercontent.com/735314/34829649-21ade7a8-f6c0-11e7-8dec-fb1441e5291e.png)

If I try to show 256 colors, most numbers are shown as blinking text.

**Comment by deadpixi** [comment]
Hi @fedemp. 

You should be getting color in mtm, for sure. What is the value of $TERM outside of mtm? Do you have a matching terminfo file for that terminal type?

Also, please try running mtm like this:

```mtm -T xterm-color```

And then rerun your test. That will force mtm to assume the host terminal is a color xterm.

**Comment by fedemp** [comment]
xfce4-terminal uses xterm-color as default. I also tested [st](https://st.suckless.org/) (my preferred terminal) which uses st-256color. Both work fine outside mtm.

`mtm -T xterm-color` does nothing different neither in in xfce4-terminal not st.

It seems I'm limited to 8 colors. On the left, vim uses bright blue.

![mtm](https://user-images.githubusercontent.com/735314/34836189-dee816d0-f6d5-11e7-89f5-b53cdfd29b5d.png)

**Comment by deadpixi** [comment]
Oh, I'm sorry, I misunderstood the issue. Yes, mtm only supports the eight colors required by the ANSI/ECMA standard (i.e. black, red, green, yellow, blue, magenta, cyan, and white).

**Comment by fedemp** [comment]
Oh, what a pity. Thanks anyways. :)
