### ISSUE TITLE
Fixing build on (Free)BSD

### ISSUE THREAD

**Issue by melak** [deadpixi/mtm#22]
I'm fixing building on FreeBSD, and there's a thing in config.h.def I'm not sure about.

```c
    49  /* Includes needed to make forkpty(3) work. */
    50  #ifndef FORKPTY_INCLUDE_H
    51      #if defined(__APPLE__) || (defined(BSD) && !defined(__linux__))
    52          #define FORKPTY_INCLUDE_H <util.h>
```

What is the `BSD` macro for? FreeBSD definitely does not define it, OSX does not define it, Linux obviously doesn't, I'm pretty sure neither do Open/Net/Dfly (although I'm not sure about these).

The `forkpty` include is slightly different across the BSDs, so this will have to be a bit more granular than just "if BSD" - at this point though, I'm not sure if it's just a placeholder of sorts, or if there's an actual use case for it I can't seem to find.

**Comment by 0mp** [comment]
I'm preparing a FreeBSD port of mtm at the moment. I've got a couple of patches we could upstream once discussed and tested.

**Comment by 0mp** [comment]
Here's a WIP port: https://github.com/0mp/freebsd-ports/tree/mtm/sysutils/mtm

@melak it would be nice if you could test it. I wonder how I can solve those termcap-related problems.

**Comment by 0mp** [comment]
mtm is now available in the FreeBSD ports. It has some issues with the termcap/terminfo stuff but otherwise it's ready to be used and tested:

https://www.freshports.org/sysutils/mtm

**Comment by melak** [comment]
It would be nice if you could make the keys configurable via port options.

**Comment by 0mp** [comment]
@melak You may look at [a patch](https://bz-attachments.freebsd.org/attachment.cgi?id=189807) attached to [this issue on FreeBSD Bugzilla](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225227). 

You may create a similar one for mtm and submit on either Bugzilla or [Phabricator](https://reviews.freebsd.org/). I'll make sure it is reviewed and pulled into the ports tree eventually. 😄

**Comment by melak** [comment]
To be honest, that is highly unlikely to happen, though :)

**Comment by deadpixi** [comment]
This is (mostly?) fixed in master now, I believe.
