### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by HackedPixels** [deadpixi/mtm#26]
It would be nice to have a simple scrolling implementation in mtm.

**Comment by nathanmiddleton** [comment]
I'm guessing this is related to how the terminal interprets the PGUP and PGDN keys, as they do show control characters. It'd be nice to not have to configure it  and account for it under bash though.  :)

**Comment by letarg0** [comment]
Ctrl+arrows or ctrl+vi keys hjkl

**Comment by deadpixi** [comment]
The master branch now has simple scrollback. :)
