### ISSUE TITLE
Fatal error when running make

### ISSUE THREAD

**Issue by syslino** [deadpixi/mtm#27]
I'm getting a ``fatal error: ncursesw/curses.h: No such file or directory`` when running ``make`` or ``make CURSESLIB=curses``.

Do I have to provide this file? Im not familiar with ncurses or even it's sources.   

I'm on a healthy, fullly updated Arch box, ncurses version 6.1-6 is installed.
I created said folder, copied ``/usr/include/curses.h`` into it but the error doesn't change a bit. Also happens with ``ncurses.h``.

Am I getting something wrong, or is this a bug? I just wanted vim bindings!

**Comment by deadpixi** [comment]
I'm not familiar with Arch, but it sounds like the wide-character version of ncurses's development files aren't installed. Make sure that's present.

If you're sure it's there, just edit config.h put

    #define NCURSESW_INCLUDE_H ...

where "..." is whatever the name of the include ends up being on Arch.

**Comment by syslino** [comment]
Sorry for replying so late, I got it to work!
I looked in the PKGBUILD (arch's way of customizing packages) and found that I just had to `make HEADERS='-DNCURSESW_INCLUDE_H="<ncurses.h>"'`
So, thank you for this fine piece of software. I was looking for _exacly_ this functionality, only with vim-bindings. Nice one!

**Comment by chanana** [comment]
I'm running Manjaro linux where in trying to do `make` gave me a similar error
```bash
cc -std=c99 -Wall -Wextra -pedantic -Os -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -o mtm  vtparser.c mtm.c  -lncursesw -lutil
In file included from mtm.c:35:
config.h:67:36: fatal error: ncursesw/curses.h: No such file or directory
   67 |         #define NCURSESW_INCLUDE_H <ncursesw/curses.h>
      |                                    ^
compilation terminated.
make: *** [Makefile:14: mtm] Error 1
```
so I went ahead and did the following:
```bash
sudo ln -s /usr/include/ncurses.h /usr/include/ncursesw/ncurses.h
```
which fixed the error. This was based on [a closed bug report](https://bugs.archlinux.org/task/13994) I found. I thought I should file this here since it worked for me and may potentially help others. :smiley:
