### ISSUE TITLE
Foreground and background color of terminal are not respected

### ISSUE THREAD

**Issue by fedemp** [deadpixi/mtm#4]
Probably a "works as expected" issue but even so I'll let you know. :)

I have my terminal emulator to use a couple of specific colors for and background and foreground color, but mtm is using colors 0 (normal black) and 7 (normal white).

**Comment by deadpixi** [comment]
It will support default colors soon. It'll be finished once things calm down at my job and I'm not working in the evenings so much. I'll update this ticket when it's done, probably this weekend or so. Thanks!

**Comment by deadpixi** [comment]
Hello @fedemp. Please try the latest code. Colors should work as expected now. I'm closing this issue, but please reopen it if you have any questions. Thanks.
