### ISSUE TITLE
no cursor in emacs

### ISSUE THREAD

**Issue by 1luhux1** [deadpixi/mtm#49]
```
out mtm $ mtm
in mtm $ emacs -Q
```
then:

![20201209_14h32m30s_grim](https://user-images.githubusercontent.com/71643947/101593805-7ac72700-39e8-11eb-98a0-f71c8fb5dc52.png)

**Comment by deadpixi** [comment]
Emacs works for me under mtm, and displays the cursor.

Would you mind trying using a different terminal emulator? Is that `xterm` in the screenshot or something else? Thanks.

**Comment by 1luhux1** [comment]
I am using alacritty, it should be an xterm compatible terminal emulator

I tried to use:

```
in mtm $ TERM=xterm-256color emacs -Q
```
To start Emacs, everything is correct

**Comment by deadpixi** [comment]
Ah, great. Yes, please consult the man page. You can have mtm report different terminal types. The default is `screen-bce`, which may not have terminfo entries on your system. Another good option might be `eterm` or `eterm-color`.
