### ISSUE TITLE
Does mtm support detaching?

### ISSUE THREAD

**Issue by tomjaguarpaw** [deadpixi/mtm#7]
Does mtm support detaching?  From the README it looks like the answer is "no".  If not, would you consider a (hypothetical) program that supports *only* detaching to be a good complement to mtm?

**Comment by deadpixi** [comment]
mtm does not, as I tried to keep it to "multiplexing only"...I think that a detaching utility would be a great complement it it.

**Comment by tomjaguarpaw** [comment]
Thanks!  I'm still looking for a program to support detaching (only).  If I find it (or write it) I'll let you know.

**Comment by jp-bennett** [comment]
@tomjaguarpaw I was pointed at http://dtach.sourceforge.net/ but haven't had time to test it out yet.

**Comment by min4builder** [comment]
[http://www.brain-dump.org/projects/abduco/](abduco) also works well.
