### ISSUE TITLE
Reduce escape time

### ISSUE THREAD

**Issue by alexherbo2** [deadpixi/mtm#9]
Escape time is too long using with [Kakoune][].

It works well with [Vim][] though.

[Kakoune]: https://github.com/mawww/kakoune
[Vim]: https://github.com/vim/vim

**Comment by deadpixi** [comment]
Please try setting and exporting the ESCDELAY environment variable to something smaller than its default before starting Kakoune. Try something like

    ESCDELAY=500 kakoune

or even

    ESCDELAY=250 kakoune

Please let me know if that works.

**Comment by alexherbo2** [comment]
It has no effect.

[Kakoune escape time][] is set to 25.

[Kakoune escape time]: https://github.com/mawww/kakoune/search?q=escdelay

**Comment by deadpixi** [comment]
Would you mind seeing the ESCDELAY to something smaller before starting mtm, so that mtm has a smaller escape time? Please let me know if that works. Thanks.

**Comment by alexherbo2** [comment]
It works!

**Comment by mazeto** [comment]
@alexherbo2, yiu forgot to close the issue.
